// Direct port of providerOptions from the original examtopics.ts
export const PROVIDER_OPTIONS = [
  { label: "Microsoft", value: "microsoft" },
  { label: "Amazon", value: "amazon" },
  { label: "Google", value: "google" },
  { label: "Cisco", value: "cisco" },
  { label: "CompTIA", value: "comptia" },
  { label: "Oracle", value: "oracle" },
  { label: "Isaca", value: "isaca" },
  { label: "VMware", value: "vmware" },
  { label: "Salesforce", value: "salesforce" },
  { label: "PMI", value: "pmi" },
  { label: "ECCouncil", value: "eccouncil" },
  { label: "ServiceNow", value: "servicenow" },
  { label: "Fortinet", value: "fortinet" },
  { label: "Dell", value: "dell" },
  { label: "Juniper", value: "juniper" },
  { label: "Checkpoint", value: "checkpoint" },
  { label: "Palo Alto Networks", value: "palo-alto-networks" },
  { label: "ISC", value: "isc" },
  { label: "HP", value: "hp" },
  { label: "Snowflake", value: "snowflake" },
  { label: "Citrix", value: "citrix" },
  { label: "IBM", value: "ibm" },
  { label: "The Open Group", value: "the-open-group" },
  { label: "Splunk", value: "splunk" },
  { label: "Netapp", value: "netapp" },
  { label: "IIA", value: "iia" },
  { label: "IIBA", value: "iiba" },
  { label: "LPI", value: "lpi" },
  { label: "PRINCE2", value: "prince2" },
  { label: "CyberArk", value: "cyberark" },
  { label: "APICS", value: "apics" },
  { label: "IAPP", value: "iapp" },
  { label: "Huawei", value: "huawei" },
  { label: "ACAMS", value: "acams" },
  { label: "Avaya", value: "avaya" },
  { label: "HashiCorp", value: "hashicorp" },
  { label: "Pegasystems", value: "pegasystems" },
  { label: "Databricks", value: "databricks" },
  { label: "Nutanix", value: "nutanix" },
  { label: "ITIL", value: "itil" },
  { label: "UiPath", value: "uipath" },
  { label: "Test Prep", value: "test-prep" },
  { label: "GIAC", value: "giac" },
  { label: "Scrum", value: "scrum" },
  { label: "Adobe", value: "adobe" },
  { label: "F5", value: "f5" },
  { label: "Mulesoft", value: "mulesoft" },
  { label: "Veeam", value: "veeam" },
  { label: "SAP", value: "sap" },
  { label: "CrowdStrike", value: "crowdstrike" },
  { label: "Alcatel-Lucent", value: "alcatel-lucent" },
  { label: "RedHat", value: "redhat" },
  { label: "Linux Foundation", value: "linux-foundation" },
  { label: "CNCF", value: "cncf" },
  { label: "Kubernetes", value: "kubernetes" },
] as const;

export type ProviderValue = (typeof PROVIDER_OPTIONS)[number]["value"];

// ─── Per-provider visual identity ─────────────────────────────────────────────

export const PROVIDER_EMOJI: Record<string, string> = {
  microsoft: "🪟",
  amazon: "☁️",
  google: "🔍",
  comptia: "🔐",
  cisco: "🌐",
  vmware: "⚡",
  oracle: "🔮",
  pmi: "📋",
  isaca: "🛡️",
  isc: "🔑",
  salesforce: "☁️",
  eccouncil: "⚔️",
  fortinet: "🔥",
  hashicorp: "🏗️",
  databricks: "💎",
  kubernetes: "☸️",
  redhat: "🎩",
  adobe: "🎨",
};

export const PROVIDER_GRADIENT: Record<string, string> = {
  microsoft: "from-blue-600 to-blue-400",
  amazon: "from-orange-500 to-amber-400",
  google: "from-green-600 to-teal-400",
  comptia: "from-red-600 to-rose-400",
  cisco: "from-blue-800 to-blue-500",
  vmware: "from-violet-600 to-purple-400",
  oracle: "from-red-700 to-orange-500",
  pmi: "from-teal-600 to-emerald-400",
  isaca: "from-indigo-600 to-blue-400",
  isc: "from-cyan-600 to-sky-400",
  salesforce: "from-sky-500 to-blue-400",
  eccouncil: "from-slate-700 to-slate-500",
  fortinet: "from-red-600 to-orange-400",
  hashicorp: "from-violet-700 to-indigo-500",
  databricks: "from-orange-600 to-red-400",
  kubernetes: "from-blue-600 to-cyan-400",
  redhat: "from-red-700 to-red-500",
  adobe: "from-red-500 to-pink-400",
};

export const DEFAULT_PROVIDER_GRADIENT = "from-primary to-primary/60";
